Add live coding for lesson 2
CohenArthur/rust-gistre-workshop pull request #31
Opened 2021-04-05 12:39 UTC by CohenArthur

2021-04-05 13:27 UTC, SanderJSA commented on 2_generics_collections/live_coding/README.md
> +# Let's implement capitalism
```suggestion
# Let's implement some banks !
```

2021-04-05 13:27 UTC, SanderJSA commented on 2_generics_collections/live_coding/README.md
> +a new account or adding money to an account (we can't lose money under capitalism, obviously).
```suggestion
a new account or adding money to an account.
```

2021-04-05 13:27 UTC, SanderJSA commented on 2_generics_collections/live_coding/README.md
> +money. On the contrary, we can have up to 18446744073709551615 monies, Jeff Bezos style.
```suggestion
We can assume that we cannot have negative money.
On the contrary, we can have up to 18446744073709551615 monies, Jeff Bezos style.
```

2021-04-05 13:27 UTC, SanderJSA commented on 2_generics_collections/live_coding/README.md
> +(not very capitalistic of you but okay).
```suggestion

```

2021-04-05 13:51 UTC, SanderJSA approved these changes

2021-04-05 20:15 UTC, Skallwar requested changes

2021-04-05 20:15 UTC, Skallwar commented on 2_generics_collections/live_coding/bank_1/src/bank.rs
> +    pub fn add_money(&mut self, account_name: &str, money_amount: Money) {
```suggestion
    /// Add money to an existing account or create a new account with `money_amount` money
    pub fn add_money(&mut self, account_name: &str, money_amount: Money) {
```

2021-04-05 20:15 UTC, Skallwar commented on 2_generics_collections/live_coding/bank_1/src/bank.rs
> +    }
From what I understand, `accounts.insert()` creates an account. I don't think we should create an account if it did not already existed. Maybe using [get_mut](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get_mut) is a better idea ? We should return an error (bool ?) if the operation did not succeed.

2021-04-07 08:35 UTC, Skallwar approved these changes

2021-04-07 08:35 UTC, merged